sudo: required

services:
  - docker

language: go

matrix:
  include:
    - go: 1.9

install:
  - hack/install-verify-tools.sh
  - export PATH=$GOPATH/bin:$PATH
  - hack/for-go-proj.sh install

script:
  - hack/verify-all.sh -v
  - hack/for-go-proj.sh test
